In [1]:
import numpy as np

In [2]:
#check all the function in numpy
print(dir(np))         # dir stands for directory

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [3]:
np.sqrt(10)    #sqrt stands for square root

3.1622776601683795

In [5]:
print('minimum -' , np.amin([12,34,56,78,])) # to know the minimum no in the list
print('maximu -' , np.amax([23,45,65,88,99,]))  #to know the maximum no in the list 

minimum - 12
maximu - 99


In [6]:
#round off to next number 
np.ceil(34.56)

35.0

In [7]:
np.ceil(np.sqrt(11))  #ceil shows next solid number or integer

4.0

In [10]:
np.ceil(np.sum(np.sqrt([5,10,15])))       #this will start work from inner side first eg here it starts work from sqrt then sum

10.0

In [11]:
np.array([5,9,13])    # array is a list in the numpy

array([ 5,  9, 13])

In [12]:
xyz = np.array([5,9,13]) # assigning variable to array

In [13]:
xyz

array([ 5,  9, 13])

In [14]:
type(xyz)  # nd means n dimesional

numpy.ndarray

In [15]:
#copy array into another variable
b = np.asarray(xyz)

In [16]:
b

array([ 5,  9, 13])

In [17]:
type(b)

numpy.ndarray

In [26]:
# dtype conversion # we want to covert data(numbers) to float


np.array([1,2,3] , dtype = float)

array([1., 2., 3.])

In [22]:
print(xyz)   # if we will print it then it will only print data

[ 5  9 13]


# DATA types:

In [28]:
my_mat = ([1,2,3] , [4,5,6] , [7,8,9])
mat = np.array(my_mat)
print("type/class of the object-" , type(mat)) #gives us the type of matrix
print("here is the matrix :\n----------\n", mat , "\n-----------" ) #gives us complete matrix 
print("dimension of the matrix :" , mat.ndim) #ndim gives dimension , 2 for a matrix , 1 for vector
print("size of the matrix :" , mat.size) # size gives total number of elements
print("shape of the matrix :" , mat.shape) # shape gives total no roes , column
print("datatype of the matrix :" , mat.dtype) #datatype is internal number in the matrix that is int ignore the 32

type/class of the object- <class 'numpy.ndarray'>
here is the matrix :
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
-----------
dimension of the matrix : 2
size of the matrix : 9
shape of the matrix : (3, 3)
datatype of the matrix : int32


# arange and linspace

In [29]:
# dont work with python range

In [32]:
list(range(2,10.5,.4))   # range do not work in python

TypeError: 'float' object cannot be interpreted as an integer

In [33]:
a = np.arange(2,10.5,.4)  #to work with float numbers we use numpy

In [34]:
a

array([ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,  4.8,  5.2,  5.6,  6. ,
        6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6, 10. , 10.4])

In [35]:
#reverse order
a[::-1]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,
        6. ,  5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [36]:
print("every 5th number from 50 in reverse order\n" , np.arange(50,-1,-5))

every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5  0]


In [37]:
print("linearly spaced number near  between 10 and 40\n-------------------------------------")
print(np.linspace(10,40,5))  #lin means linear space equal distance 
# 5 means 5 points with equal distance from each other

linearly spaced number near  between 10 and 40
-------------------------------------
[10.  17.5 25.  32.5 40. ]


In [38]:
print(np.linspace(10,80,7))  #total no = 7 ,equally spaced between them

[10.         21.66666667 33.33333333 45.         56.66666667 68.33333333
 80.        ]


In [39]:
print(np.linspace(10,100,17))

[ 10.     15.625  21.25   26.875  32.5    38.125  43.75   49.375  55.
  60.625  66.25   71.875  77.5    83.125  88.75   94.375 100.   ]


In [40]:
print(np.linspace(4.56782,24.56782,45))  # we dont know the difference b/w each no is unknown here thats why we use retstep

[ 4.56782     5.02236545  5.47691091  5.93145636  6.38600182  6.84054727
  7.29509273  7.74963818  8.20418364  8.65872909  9.11327455  9.56782
 10.02236545 10.47691091 10.93145636 11.38600182 11.84054727 12.29509273
 12.74963818 13.20418364 13.65872909 14.11327455 14.56782    15.02236545
 15.47691091 15.93145636 16.38600182 16.84054727 17.29509273 17.74963818
 18.20418364 18.65872909 19.11327455 19.56782    20.02236545 20.47691091
 20.93145636 21.38600182 21.84054727 22.29509273 22.74963818 23.20418364
 23.65872909 24.11327455 24.56782   ]


In [42]:
#include endpoint and check space between them 
#by default endpoint = true
#by default retspace = False
np.linspace(2,3,num = 4 , endpoint = False , retstep= True ) # to exclude 3 which is endpoint , endpoint = false 
# to include difference retstep (difference b/w each number ) , retstep = true

(array([2.  , 2.25, 2.5 , 2.75]), 0.25)

# matrix creation

In [44]:
print("vectors of zero\n---------------------")
print(np.zeros(5))

vectors of zero
---------------------
[0. 0. 0. 0. 0.]


In [46]:
print("matrix ofzero\n---------------------------")
print(np.zeros((5,6))) #(5,6) is the shape dimension of matrix , rows and column , 5 rows 6 column

matrix ofzero
---------------------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [47]:
print("matrix ofzero\n---------------------------")
print(np.ones((5,6))) #note matrix dimension specified by tuples

matrix ofzero
---------------------------
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [48]:
print("matrix of five\n--------------------------")
print( 5 * np.ones ((4,3)))

matrix of five
--------------------------
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [51]:
# construct diagonal matrix
x = np.arange(30).reshape(10,3)


print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


In [52]:
# construct diagonal matrix
x = np.arange(30).reshape(5,6)


print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


# random number generation:

In [53]:
np.random.seed(6)      #each seed no will generate similar data.

print("random number generation(from unifrom distribution)")

print(np.random.rand(10,6)) # seed helps in getting the same data again and again doesn't matter how many times we run the same cell
# and why use the 6 here is because every number holds some type of randomness. we can use any number in place of 6

random number generation(from unifrom distribution)
[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [54]:
np.random.seed(6123)      

print("random number generation(from unifrom distribution)")

print(np.random.rand(10,6))

random number generation(from unifrom distribution)
[[0.70520927 0.70351865 0.29319836 0.76301519 0.35916327 0.52509784]
 [0.31946636 0.00134285 0.94842794 0.23558152 0.41011829 0.37300443]
 [0.22178518 0.23243736 0.61787196 0.12932121 0.39207568 0.57143362]
 [0.23353383 0.75595409 0.4917942  0.93327838 0.56421128 0.08792537]
 [0.22642318 0.08454764 0.84387775 0.12342299 0.94074404 0.48608003]
 [0.72891699 0.01624727 0.75172223 0.03066134 0.19533859 0.26522479]
 [0.3330888  0.67277569 0.72954018 0.0853452  0.67825972 0.12029013]
 [0.23423637 0.11123627 0.9912454  0.32157218 0.03507554 0.40339873]
 [0.14711327 0.6484357  0.72073438 0.92262773 0.01425628 0.85924666]
 [0.61070022 0.22477612 0.737819   0.2677083  0.31352596 0.42954232]]


In [ ]:
#rand = show all positive numbers and the difference between numbers is uniform(means it is less than 1 )

#randn  = it will take both neg and positive value.and we avg all the numbers the avg will be close to 0 and it will make shape of bell shaped curve or normal distribution

#

In [55]:
np.random.seed(6)      #each seed no will generate similar data.

print("random number generation(from unifrom distribution)")

print(np.random.randn(10,6))

random number generation(from unifrom distribution)
[[-0.31178367  0.72900392  0.21782079 -0.8990918  -2.48678065  0.91325152]
 [ 1.12706373 -1.51409323  1.63929108 -0.4298936   2.63128056  0.60182225]
 [-0.33588161  1.23773784  0.11112817  0.12915125  0.07612761 -0.15512816]
 [ 0.63422534  0.810655    0.35480861  1.81259031 -1.3564758  -0.46363197]
 [ 0.82465384 -1.17643148  1.56448966  0.71270509 -0.1810066   0.53419953]
 [-0.58661296 -1.48185327  0.85724762  0.94309899  0.11444143 -0.02195668]
 [-2.12714455 -0.83440747 -0.46550831  0.23371059  1.38503523 -0.51962709]
 [-0.78015214  0.95560959 -0.12673638 -1.36861282  1.21848065 -0.85750144]
 [-0.56147088 -1.0335199   0.35877096  1.07368134 -0.37550472  0.39636757]
 [-0.47144628  2.33660781  1.50278553 -0.59545972  0.52834106  0.9398248 ]]


In [58]:
print("numbers from normal distribution with zero mean and standard deviation 1 i.e. standard normal ")
print(np.random.randn(10,6))

numbers from normal distribution with zero mean and standard deviation 1 i.e. standard normal 
[[-0.31178367  0.72900392  0.21782079 -0.8990918  -2.48678065  0.91325152]
 [ 1.12706373 -1.51409323  1.63929108 -0.4298936   2.63128056  0.60182225]
 [-0.33588161  1.23773784  0.11112817  0.12915125  0.07612761 -0.15512816]
 [ 0.63422534  0.810655    0.35480861  1.81259031 -1.3564758  -0.46363197]
 [ 0.82465384 -1.17643148  1.56448966  0.71270509 -0.1810066   0.53419953]
 [-0.58661296 -1.48185327  0.85724762  0.94309899  0.11444143 -0.02195668]
 [-2.12714455 -0.83440747 -0.46550831  0.23371059  1.38503523 -0.51962709]
 [-0.78015214  0.95560959 -0.12673638 -1.36861282  1.21848065 -0.85750144]
 [-0.56147088 -1.0335199   0.35877096  1.07368134 -0.37550472  0.39636757]
 [-0.47144628  2.33660781  1.50278553 -0.59545972  0.52834106  0.9398248 ]]


In [59]:
print("random integer vector:" , np.random.randint(5,234566772 , 100))
#randit = we have to first select our range and total numbers we want and in includes duplicate number

random integer vector: [ 61296096 113432865  65820625  45029948 139618099  22185569 150966227
 213862618   3661380 129289073 100036358 106672113  97846880 165307916
  99751657 110377911   6932701  17215460 177706413 126564434  91150380
  39350909  15979349 190466287  55577681   5633330 123680433 204795005
 150366036  16223550 137126871 103826434 177668005  27534545 106144499
  67677107 234217628  23205275  98570933  21334828  73114336 230347306
 227065456 141088387 157232422 131169245  12470762  26204078 217026464
 158447160 200608612  43587916 105275888  67244938  62243272 113174349
 201025876   2827564   1207215 164902666  74470462 137741928 107524221
  44763493 233673500 105655681 142836316 195405220   9611413 179310056
 231427018 110193394 185275143  40968177   3833704  59213075 154643993
   8291458   1848866 148157118 222035405 183534699 144334531  18758248
  53668887  58513510 214925261  13346397  18454478  42880677 216545100
 138187003   1186453 139738486  52502637  60708650 206

In [62]:
print("\nrandom integer matrix")
print(np.random.randint(1,30000 ,(6,7)))  #we are giving shape here(6,7) 


random integer matrix
[[ 2734 21158 25290   829 17517  6594  1395]
 [ 7962 21018  5798 12764 19415  9173  6417]
 [24645 22243 29623 12768 14531 27917 28466]
 [18992 15887 11359 24475 25578 28403 16705]
 [18780 18307 15355 11222 24641 15656  8972]
 [  599  3367 25489    10 16534 12574 19711]]
